'''
This file is used to transform the induction loop data so that it can be used as an input for CaDyTS/MATSim.
Please note that the counts are generated for each street in their own xml file.
The counts file can then be generated by combining the contents of all generated files into one.
It has to be noted that the 24 MQ10.1 values have to be introduced by hand.
'''

import os
import xml.etree.ElementTree as ET

# full dataset as an input file here, contains corresponding
data_sets = [
    # Konrad Adenauer Brucke
    # MQ1-Stundenwerte, left richtung ma, rechts richtung lu
    ("""
16.05.2023 01:00;MQ 1.1 KAB Ri MA;80,8;;MQ 1.2 KAB Ri LU;140,1;  
16.05.2023 02:00;MQ 1.1 KAB Ri MA;37,1;;MQ 1.2 KAB Ri LU;105,5;  
16.05.2023 03:00;MQ 1.1 KAB Ri MA;30;;MQ 1.2 KAB Ri LU;63;  
16.05.2023 04:00;MQ 1.1 KAB Ri MA;58,9;;MQ 1.2 KAB Ri LU;52;  
16.05.2023 05:00;MQ 1.1 KAB Ri MA;99,4;;MQ 1.2 KAB Ri LU;130,9;  
16.05.2023 06:00;MQ 1.1 KAB Ri MA;505,2;;MQ 1.2 KAB Ri LU;459;  
16.05.2023 07:00;MQ 1.1 KAB Ri MA;735,7;;MQ 1.2 KAB Ri LU;915,9;  
16.05.2023 08:00;MQ 1.1 KAB Ri MA;992,1;;MQ 1.2 KAB Ri LU;1.186,30;  
16.05.2023 09:00;MQ 1.1 KAB Ri MA;1.060,00;;MQ 1.2 KAB Ri LU;1.063,70;  
16.05.2023 10:00;MQ 1.1 KAB Ri MA;695,3;;MQ 1.2 KAB Ri LU;819,8;  
16.05.2023 11:00;MQ 1.1 KAB Ri MA;546,6;;MQ 1.2 KAB Ri LU;831,5;  
16.05.2023 12:00;MQ 1.1 KAB Ri MA;489,7;;MQ 1.2 KAB Ri LU;906,7;  
16.05.2023 13:00;MQ 1.1 KAB Ri MA;555,1;;MQ 1.2 KAB Ri LU;1.087,10;  
16.05.2023 14:00;MQ 1.1 KAB Ri MA;608,4;;MQ 1.2 KAB Ri LU;1.097,10;  
16.05.2023 15:00;MQ 1.1 KAB Ri MA;632,4;;MQ 1.2 KAB Ri LU;1.120,40;  
16.05.2023 16:00;MQ 1.1 KAB Ri MA;676;;MQ 1.2 KAB Ri LU;994,6;  
16.05.2023 17:00;MQ 1.1 KAB Ri MA;801,1;;MQ 1.2 KAB Ri LU;956,1;  
16.05.2023 18:00;MQ 1.1 KAB Ri MA;724,5;;MQ 1.2 KAB Ri LU;881,3;  
16.05.2023 19:00;MQ 1.1 KAB Ri MA;527,1;;MQ 1.2 KAB Ri LU;952,4;  
16.05.2023 20:00;MQ 1.1 KAB Ri MA;406,2;;MQ 1.2 KAB Ri LU;807,9;  
16.05.2023 21:00;MQ 1.1 KAB Ri MA;287,2;;MQ 1.2 KAB Ri LU;688,3;  
16.05.2023 22:00;MQ 1.1 KAB Ri MA;253,3;;MQ 1.2 KAB Ri LU;614,6;  
16.05.2023 23:00;MQ 1.1 KAB Ri MA;167;;MQ 1.2 KAB Ri LU;589,9;  
16.05.2023 23:59;MQ 1.1 KAB Ri MA;106,9;;MQ 1.2 KAB Ri LU;668,3;  
""", '242299', 'link_242299', '218990', 'link_218990'),
    # Kurt Schumacher brucke
    # mq2 stundenwerte, left richtung lu, right richtung ma
    ("""16.05.2023 01:00;MQ 2.2 KSB Ri LU;189;;MQ 2.1 KSB Ri MA;206;
16.05.2023 02:00;MQ 2.2 KSB Ri LU;124;;MQ 2.1 KSB Ri MA;165;
16.05.2023 03:00;MQ 2.2 KSB Ri LU;82;;MQ 2.1 KSB Ri MA;107;
16.05.2023 04:00;MQ 2.2 KSB Ri LU;102;;MQ 2.1 KSB Ri MA;189;
16.05.2023 05:00;MQ 2.2 KSB Ri LU;284;;MQ 2.1 KSB Ri MA;535;
16.05.2023 06:00;MQ 2.2 KSB Ri LU;750;;MQ 2.1 KSB Ri MA;1.888,00;
16.05.2023 07:00;MQ 2.2 KSB Ri LU;1.545,00;;MQ 2.1 KSB Ri MA;2.595,50;
16.05.2023 08:00;MQ 2.2 KSB Ri LU;1.872,00;;MQ 2.1 KSB Ri MA;2.663,00;
16.05.2023 09:00;MQ 2.2 KSB Ri LU;1.578,00;;MQ 2.1 KSB Ri MA;2.588,00;
16.05.2023 10:00;MQ 2.2 KSB Ri LU;1.280,00;;MQ 2.1 KSB Ri MA;2.256,00;
16.05.2023 11:00;MQ 2.2 KSB Ri LU;1.293,00;;MQ 2.1 KSB Ri MA;1.926,00;
16.05.2023 12:00;MQ 2.2 KSB Ri LU;1.306,00;;MQ 2.1 KSB Ri MA;1.889,00;
16.05.2023 13:00;MQ 2.2 KSB Ri LU;1.603,00;;MQ 2.1 KSB Ri MA;1.941,00;
16.05.2023 14:00;MQ 2.2 KSB Ri LU;1.826,00;;MQ 2.1 KSB Ri MA;2.058,00;
16.05.2023 15:00;MQ 2.2 KSB Ri LU;2.380,00;;MQ 2.1 KSB Ri MA;2.180,00;
16.05.2023 16:00;MQ 2.2 KSB Ri LU;2.245,20;;MQ 2.1 KSB Ri MA;2.387,00;
16.05.2023 17:00;MQ 2.2 KSB Ri LU;2.429,00;;MQ 2.1 KSB Ri MA;2.462,00;
16.05.2023 18:00;MQ 2.2 KSB Ri LU;2.550,00;;MQ 2.1 KSB Ri MA;2.635,00;
16.05.2023 19:00;MQ 2.2 KSB Ri LU;2.158,00;;MQ 2.1 KSB Ri MA;2.259,00;
16.05.2023 20:00;MQ 2.2 KSB Ri LU;1.413,00;;MQ 2.1 KSB Ri MA;1.568,00;
16.05.2023 21:00;MQ 2.2 KSB Ri LU;1.121,00;;MQ 2.1 KSB Ri MA;1.232,00;
16.05.2023 22:00;MQ 2.2 KSB Ri LU;968;;MQ 2.1 KSB Ri MA;1.029,00;
16.05.2023 23:00;MQ 2.2 KSB Ri LU;924;;MQ 2.1 KSB Ri MA;717;
16.05.2023 23:59;MQ 2.2 KSB Ri LU;650,8;;MQ 2.1 KSB Ri MA;488,3;
""", '197907', 'link_197907', '379043', 'link_379043'),
    # mq3luisenring / parkring strase, left ri parkring, right ri Luisenring
    ("""
16.05.2023 01:00;MQ 3.1 Flyover Ri Parkring;43;;MQ 3.2 Flyover Ri Luisenring;96;
16.05.2023 02:00;MQ 3.1 Flyover Ri Parkring;27;;MQ 3.2 Flyover Ri Luisenring;51;
16.05.2023 03:00;MQ 3.1 Flyover Ri Parkring;33;;MQ 3.2 Flyover Ri Luisenring;26;
16.05.2023 04:00;MQ 3.1 Flyover Ri Parkring;31;;MQ 3.2 Flyover Ri Luisenring;59;
16.05.2023 05:00;MQ 3.1 Flyover Ri Parkring;50;;MQ 3.2 Flyover Ri Luisenring;94;
16.05.2023 06:00;MQ 3.1 Flyover Ri Parkring;254;;MQ 3.2 Flyover Ri Luisenring;434;
16.05.2023 07:00;MQ 3.1 Flyover Ri Parkring;377;;MQ 3.2 Flyover Ri Luisenring;364;
16.05.2023 08:00;MQ 3.1 Flyover Ri Parkring;539;;MQ 3.2 Flyover Ri Luisenring;402;
16.05.2023 09:00;MQ 3.1 Flyover Ri Parkring;557;;MQ 3.2 Flyover Ri Luisenring;432;
16.05.2023 10:00;MQ 3.1 Flyover Ri Parkring;461;;MQ 3.2 Flyover Ri Luisenring;387;
16.05.2023 11:00;MQ 3.1 Flyover Ri Parkring;367;;MQ 3.2 Flyover Ri Luisenring;438;
16.05.2023 12:00;MQ 3.1 Flyover Ri Parkring;381;;MQ 3.2 Flyover Ri Luisenring;379;
16.05.2023 13:00;MQ 3.1 Flyover Ri Parkring;382;;MQ 3.2 Flyover Ri Luisenring;477;
16.05.2023 14:00;MQ 3.1 Flyover Ri Parkring;394;;MQ 3.2 Flyover Ri Luisenring;471;
16.05.2023 15:00;MQ 3.1 Flyover Ri Parkring;479;;MQ 3.2 Flyover Ri Luisenring;569;
16.05.2023 16:00;MQ 3.1 Flyover Ri Parkring;377;;MQ 3.2 Flyover Ri Luisenring;563,3;
16.05.2023 17:00;MQ 3.1 Flyover Ri Parkring;417;;MQ 3.2 Flyover Ri Luisenring;610;
16.05.2023 18:00;MQ 3.1 Flyover Ri Parkring;397;;MQ 3.2 Flyover Ri Luisenring;499;
16.05.2023 19:00;MQ 3.1 Flyover Ri Parkring;378;;MQ 3.2 Flyover Ri Luisenring;393;
16.05.2023 20:00;MQ 3.1 Flyover Ri Parkring;235;;MQ 3.2 Flyover Ri Luisenring;253;
16.05.2023 21:00;MQ 3.1 Flyover Ri Parkring;261;;MQ 3.2 Flyover Ri Luisenring;231;
16.05.2023 22:00;MQ 3.1 Flyover Ri Parkring;180;;MQ 3.2 Flyover Ri Luisenring;191;
16.05.2023 23:00;MQ 3.1 Flyover Ri Parkring;174;;MQ 3.2 Flyover Ri Luisenring;149;
16.05.2023 23:59;MQ 3.1 Flyover Ri Parkring;94;;MQ 3.2 Flyover Ri Luisenring;160,4;"""
     , '199024', 'link_199024', '241331', 'link_241331'
     ),
    # mq4 left neckarstadt richtung innestadt, right innenstadt richtung neckarstadt
    # left <!--MQ4 Jungbuschbrucke richtung innenstadt-->
    # right <!--MQ4 Jungbuschbrucke richtung Neckarstadt-->
    ("""16.05.2023 01:00;MQ 4.1 JBB Ri Innenstadt;135;;MQ 4.2 JBB Ri Neckarstadt;152;
16.05.2023 02:00;MQ 4.1 JBB Ri Innenstadt;72;;MQ 4.2 JBB Ri Neckarstadt;73;
16.05.2023 03:00;MQ 4.1 JBB Ri Innenstadt;59;;MQ 4.2 JBB Ri Neckarstadt;60;
16.05.2023 04:00;MQ 4.1 JBB Ri Innenstadt;66;;MQ 4.2 JBB Ri Neckarstadt;82;
16.05.2023 05:00;MQ 4.1 JBB Ri Innenstadt;151;;MQ 4.2 JBB Ri Neckarstadt;279,9;
16.05.2023 06:00;MQ 4.1 JBB Ri Innenstadt;628;;MQ 4.2 JBB Ri Neckarstadt;1.099,70;
16.05.2023 07:00;MQ 4.1 JBB Ri Innenstadt;1.047,00;;MQ 4.2 JBB Ri Neckarstadt;1.201,00;
16.05.2023 08:00;MQ 4.1 JBB Ri Innenstadt;1.428,00;;MQ 4.2 JBB Ri Neckarstadt;1.241,10;
16.05.2023 09:00;MQ 4.1 JBB Ri Innenstadt;1.368,00;;MQ 4.2 JBB Ri Neckarstadt;1.206,90;
16.05.2023 10:00;MQ 4.1 JBB Ri Innenstadt;1.069,00;;MQ 4.2 JBB Ri Neckarstadt;1.035,10;
16.05.2023 11:00;MQ 4.1 JBB Ri Innenstadt;977;;MQ 4.2 JBB Ri Neckarstadt;1.042,00;
16.05.2023 12:00;MQ 4.1 JBB Ri Innenstadt;921;;MQ 4.2 JBB Ri Neckarstadt;983;
16.05.2023 13:00;MQ 4.1 JBB Ri Innenstadt;966;;MQ 4.2 JBB Ri Neckarstadt;1.184,90;
16.05.2023 14:00;MQ 4.1 JBB Ri Innenstadt;1.063,00;;MQ 4.2 JBB Ri Neckarstadt;1.358,00;
16.05.2023 15:00;MQ 4.1 JBB Ri Innenstadt;1.553,00;;MQ 4.2 JBB Ri Neckarstadt;1.434,00;
16.05.2023 16:00;MQ 4.1 JBB Ri Innenstadt;1.482,00;;MQ 4.2 JBB Ri Neckarstadt;1.346,00;
16.05.2023 17:00;MQ 4.1 JBB Ri Innenstadt;1.396,00;;MQ 4.2 JBB Ri Neckarstadt;1.562,00;
16.05.2023 18:00;MQ 4.1 JBB Ri Innenstadt;1.217,00;;MQ 4.2 JBB Ri Neckarstadt;1.383,10;
16.05.2023 19:00;MQ 4.1 JBB Ri Innenstadt;1.076,00;;MQ 4.2 JBB Ri Neckarstadt;1.056,00;
16.05.2023 20:00;MQ 4.1 JBB Ri Innenstadt;693;;MQ 4.2 JBB Ri Neckarstadt;797;
16.05.2023 21:00;MQ 4.1 JBB Ri Innenstadt;528;;MQ 4.2 JBB Ri Neckarstadt;667;
16.05.2023 22:00;MQ 4.1 JBB Ri Innenstadt;518;;MQ 4.2 JBB Ri Neckarstadt;584,1;
16.05.2023 23:00;MQ 4.1 JBB Ri Innenstadt;452;;MQ 4.2 JBB Ri Neckarstadt;430,1;
16.05.2023 23:59;MQ 4.1 JBB Ri Innenstadt;338;;MQ 4.2 JBB Ri Neckarstadt;323;"""
     , '209205', 'link_209205', '232198', 'link_232198'),
    # left<!--MQ5 Kurpfalzbrucke Richtung Innenstadt-->
    # right<!--MQ5 Kurpfalzbrucke Richtung Neckarstadt-->
    ("""16.05.2023 01:00;MQ 5.1 KPB Ri Innenstadt;85;;MQ 5.2 KPB Ri Neckarstadt;118;
16.05.2023 02:00;MQ 5.1 KPB Ri Innenstadt;52;;MQ 5.2 KPB Ri Neckarstadt;75;
16.05.2023 03:00;MQ 5.1 KPB Ri Innenstadt;38;;MQ 5.2 KPB Ri Neckarstadt;42;
16.05.2023 04:00;MQ 5.1 KPB Ri Innenstadt;55;;MQ 5.2 KPB Ri Neckarstadt;43;
16.05.2023 05:00;MQ 5.1 KPB Ri Innenstadt;104;;MQ 5.2 KPB Ri Neckarstadt;74;
16.05.2023 06:00;MQ 5.1 KPB Ri Innenstadt;297;;MQ 5.2 KPB Ri Neckarstadt;251;
16.05.2023 07:00;MQ 5.1 KPB Ri Innenstadt;545;;MQ 5.2 KPB Ri Neckarstadt;450;
16.05.2023 08:00;MQ 5.1 KPB Ri Innenstadt;723;;MQ 5.2 KPB Ri Neckarstadt;723;
16.05.2023 09:00;MQ 5.1 KPB Ri Innenstadt;731;;MQ 5.2 KPB Ri Neckarstadt;691;
16.05.2023 10:00;MQ 5.1 KPB Ri Innenstadt;622;;MQ 5.2 KPB Ri Neckarstadt;588;
16.05.2023 11:00;MQ 5.1 KPB Ri Innenstadt;569;;MQ 5.2 KPB Ri Neckarstadt;640;
16.05.2023 12:00;MQ 5.1 KPB Ri Innenstadt;600;;MQ 5.2 KPB Ri Neckarstadt;679;
16.05.2023 13:00;MQ 5.1 KPB Ri Innenstadt;535;;MQ 5.2 KPB Ri Neckarstadt;727;
16.05.2023 14:00;MQ 5.1 KPB Ri Innenstadt;630;;MQ 5.2 KPB Ri Neckarstadt;744;
16.05.2023 15:00;MQ 5.1 KPB Ri Innenstadt;665;;MQ 5.2 KPB Ri Neckarstadt;734;
16.05.2023 16:00;MQ 5.1 KPB Ri Innenstadt;768;;MQ 5.2 KPB Ri Neckarstadt;827;
16.05.2023 17:00;MQ 5.1 KPB Ri Innenstadt;808;;MQ 5.2 KPB Ri Neckarstadt;927;
16.05.2023 18:00;MQ 5.1 KPB Ri Innenstadt;686;;MQ 5.2 KPB Ri Neckarstadt;931;
16.05.2023 19:00;MQ 5.1 KPB Ri Innenstadt;604;;MQ 5.2 KPB Ri Neckarstadt;796;
16.05.2023 20:00;MQ 5.1 KPB Ri Innenstadt;484;;MQ 5.2 KPB Ri Neckarstadt;627;
16.05.2023 21:00;MQ 5.1 KPB Ri Innenstadt;415;;MQ 5.2 KPB Ri Neckarstadt;524;
16.05.2023 22:00;MQ 5.1 KPB Ri Innenstadt;327;;MQ 5.2 KPB Ri Neckarstadt;464;
16.05.2023 23:00;MQ 5.1 KPB Ri Innenstadt;290;;MQ 5.2 KPB Ri Neckarstadt;372;
16.05.2023 23:59;MQ 5.1 KPB Ri Innenstadt;212;;MQ 5.2 KPB Ri Neckarstadt;303;""",
     '195706', 'link_195706', '243769', 'link_243769'
     ),
    # left	<!--MQ6 Friedrich-Ebert-Brucke Richtung Innenstadt-->
    # right <!--MQ6 Friedrich-Ebert-Brucke Richtung Neckarstadt-->
    (
        """16.05.2023 01:00;MQ 6.1 FEB Ri Innenstadt;105;;MQ 6.2 FEB Ri Neckarstadt;207;
16.05.2023 02:00;MQ 6.1 FEB Ri Innenstadt;63;;MQ 6.2 FEB Ri Neckarstadt;134;
16.05.2023 03:00;MQ 6.1 FEB Ri Innenstadt;51;;MQ 6.2 FEB Ri Neckarstadt;90;
16.05.2023 04:00;MQ 6.1 FEB Ri Innenstadt;62;;MQ 6.2 FEB Ri Neckarstadt;40;
16.05.2023 05:00;MQ 6.1 FEB Ri Innenstadt;121;;MQ 6.2 FEB Ri Neckarstadt;113;
16.05.2023 06:00;MQ 6.1 FEB Ri Innenstadt;425;;MQ 6.2 FEB Ri Neckarstadt;469;
16.05.2023 07:00;MQ 6.1 FEB Ri Innenstadt;909;;MQ 6.2 FEB Ri Neckarstadt;842;
16.05.2023 08:00;MQ 6.1 FEB Ri Innenstadt;1.388,00;;MQ 6.2 FEB Ri Neckarstadt;1.371,00;
16.05.2023 09:00;MQ 6.1 FEB Ri Innenstadt;1.643,00;;MQ 6.2 FEB Ri Neckarstadt;1.386,00;
16.05.2023 10:00;MQ 6.1 FEB Ri Innenstadt;1.280,00;;MQ 6.2 FEB Ri Neckarstadt;1.273,00;
16.05.2023 11:00;MQ 6.1 FEB Ri Innenstadt;1.256,00;;MQ 6.2 FEB Ri Neckarstadt;1.250,00;
16.05.2023 12:00;MQ 6.1 FEB Ri Innenstadt;1.207,00;;MQ 6.2 FEB Ri Neckarstadt;1.376,00;
16.05.2023 13:00;MQ 6.1 FEB Ri Innenstadt;1.197,00;;MQ 6.2 FEB Ri Neckarstadt;1.458,00;
16.05.2023 14:00;MQ 6.1 FEB Ri Innenstadt;1.226,00;;MQ 6.2 FEB Ri Neckarstadt;1.538,00;
16.05.2023 15:00;MQ 6.1 FEB Ri Innenstadt;1.233,00;;MQ 6.2 FEB Ri Neckarstadt;1.557,00;
16.05.2023 16:00;MQ 6.1 FEB Ri Innenstadt;1.199,00;;MQ 6.2 FEB Ri Neckarstadt;1.783,00;
16.05.2023 17:00;MQ 6.1 FEB Ri Innenstadt;1.122,00;;MQ 6.2 FEB Ri Neckarstadt;1.877,00;
16.05.2023 18:00;MQ 6.1 FEB Ri Innenstadt;1.315,00;;MQ 6.2 FEB Ri Neckarstadt;1.741,00;
16.05.2023 19:00;MQ 6.1 FEB Ri Innenstadt;1.177,00;;MQ 6.2 FEB Ri Neckarstadt;1.627,00;
16.05.2023 20:00;MQ 6.1 FEB Ri Innenstadt;891;;MQ 6.2 FEB Ri Neckarstadt;1.183,00;
16.05.2023 21:00;MQ 6.1 FEB Ri Innenstadt;681;;MQ 6.2 FEB Ri Neckarstadt;1.012,00;
16.05.2023 22:00;MQ 6.1 FEB Ri Innenstadt;538;;MQ 6.2 FEB Ri Neckarstadt;769;
16.05.2023 23:00;MQ 6.1 FEB Ri Innenstadt;338;;MQ 6.2 FEB Ri Neckarstadt;746;
16.05.2023 23:59;MQ 6.1 FEB Ri Innenstadt;254;;MQ 6.2 FEB Ri Neckarstadt;358;""",
        '135335', 'link_135335', '58483', 'link_58483'
    ),
    #	<!--MQ7 Carlo Schmidt Brucke richtung Necakarau-->
    # <!--MQ7 Carlo Schmidt Brucke richtung Feudenheim-->
    ("""16.05.2023 01:00;MQ 7.1 CSB Ri Neckarau;120;;MQ 7.2 CSB Ri Feudenheim;157;
16.05.2023 02:00;MQ 7.1 CSB Ri Neckarau;87;;MQ 7.2 CSB Ri Feudenheim;124;
16.05.2023 03:00;MQ 7.1 CSB Ri Neckarau;75;;MQ 7.2 CSB Ri Feudenheim;76;
16.05.2023 04:00;MQ 7.1 CSB Ri Neckarau;74;;MQ 7.2 CSB Ri Feudenheim;87;
16.05.2023 05:00;MQ 7.1 CSB Ri Neckarau;180;;MQ 7.2 CSB Ri Feudenheim;308;
16.05.2023 06:00;MQ 7.1 CSB Ri Neckarau;812;;MQ 7.2 CSB Ri Feudenheim;1.029,00;
16.05.2023 07:00;MQ 7.1 CSB Ri Neckarau;1.575,00;;MQ 7.2 CSB Ri Feudenheim;1.602,00;
16.05.2023 08:00;MQ 7.1 CSB Ri Neckarau;2.564,00;;MQ 7.2 CSB Ri Feudenheim;2.318,00;
16.05.2023 09:00;MQ 7.1 CSB Ri Neckarau;2.569,00;;MQ 7.2 CSB Ri Feudenheim;2.149,00;
16.05.2023 10:00;MQ 7.1 CSB Ri Neckarau;1.764,00;;MQ 7.2 CSB Ri Feudenheim;1.781,00;
16.05.2023 11:00;MQ 7.1 CSB Ri Neckarau;1.597,00;;MQ 7.2 CSB Ri Feudenheim;1.629,00;
16.05.2023 12:00;MQ 7.1 CSB Ri Neckarau;1.652,00;;MQ 7.2 CSB Ri Feudenheim;1.726,00;
16.05.2023 13:00;MQ 7.1 CSB Ri Neckarau;1.791,00;;MQ 7.2 CSB Ri Feudenheim;1.885,00;
16.05.2023 14:00;MQ 7.1 CSB Ri Neckarau;1.881,00;;MQ 7.2 CSB Ri Feudenheim;1.948,00;
16.05.2023 15:00;MQ 7.1 CSB Ri Neckarau;2.073,00;;MQ 7.2 CSB Ri Feudenheim;2.159,00;
16.05.2023 16:00;MQ 7.1 CSB Ri Neckarau;2.442,00;;MQ 7.2 CSB Ri Feudenheim;2.518,00;
16.05.2023 17:00;MQ 7.1 CSB Ri Neckarau;2.534,00;;MQ 7.2 CSB Ri Feudenheim;2.579,00;
16.05.2023 18:00;MQ 7.1 CSB Ri Neckarau;2.324,00;;MQ 7.2 CSB Ri Feudenheim;2.645,00;
16.05.2023 19:00;MQ 7.1 CSB Ri Neckarau;1.769,00;;MQ 7.2 CSB Ri Feudenheim;2.040,00;
16.05.2023 20:00;MQ 7.1 CSB Ri Neckarau;1.225,00;;MQ 7.2 CSB Ri Feudenheim;1.469,00;
16.05.2023 21:00;MQ 7.1 CSB Ri Neckarau;827;;MQ 7.2 CSB Ri Feudenheim;1.099,00;
16.05.2023 22:00;MQ 7.1 CSB Ri Neckarau;656;;MQ 7.2 CSB Ri Feudenheim;962;
16.05.2023 23:00;MQ 7.1 CSB Ri Neckarau;503;;MQ 7.2 CSB Ri Feudenheim;712;
16.05.2023 23:59;MQ 7.1 CSB Ri Neckarau;317;;MQ 7.2 CSB Ri Feudenheim;653;""",
     '298916', 'link_298916', '230430', 'link_230430'),
    # <!--MQ 8 Ludwigshafener Strase richtung Ludwigshafen -->
    # <!--MQ 8 Ludwigshafener strase richtung neuhermsheim -->
    (
        """16.05.2023 01:00;MQ 8.1 FLT Ri LU;45;;MQ 8.2 FLT Ri Neuhermsheim;54;
16.05.2023 02:00;MQ 8.1 FLT Ri LU;24;;MQ 8.2 FLT Ri Neuhermsheim;29;
16.05.2023 03:00;MQ 8.1 FLT Ri LU;27;;MQ 8.2 FLT Ri Neuhermsheim;26;
16.05.2023 04:00;MQ 8.1 FLT Ri LU;32;;MQ 8.2 FLT Ri Neuhermsheim;67;
16.05.2023 05:00;MQ 8.1 FLT Ri LU;84;;MQ 8.2 FLT Ri Neuhermsheim;99;
16.05.2023 06:00;MQ 8.1 FLT Ri LU;515;;MQ 8.2 FLT Ri Neuhermsheim;301;
16.05.2023 07:00;MQ 8.1 FLT Ri LU;717;;MQ 8.2 FLT Ri Neuhermsheim;519;
16.05.2023 08:00;MQ 8.1 FLT Ri LU;1.097,00;;MQ 8.2 FLT Ri Neuhermsheim;702;
16.05.2023 09:00;MQ 8.1 FLT Ri LU;1.173,00;;MQ 8.2 FLT Ri Neuhermsheim;653;
16.05.2023 10:00;MQ 8.1 FLT Ri LU;754;;MQ 8.2 FLT Ri Neuhermsheim;518;
16.05.2023 11:00;MQ 8.1 FLT Ri LU;646;;MQ 8.2 FLT Ri Neuhermsheim;474;
16.05.2023 12:00;MQ 8.1 FLT Ri LU;586;;MQ 8.2 FLT Ri Neuhermsheim;459;
16.05.2023 13:00;MQ 8.1 FLT Ri LU;608;;MQ 8.2 FLT Ri Neuhermsheim;559;
16.05.2023 14:00;MQ 8.1 FLT Ri LU;742;;MQ 8.2 FLT Ri Neuhermsheim;605;
16.05.2023 15:00;MQ 8.1 FLT Ri LU;800;;MQ 8.2 FLT Ri Neuhermsheim;763;
16.05.2023 16:00;MQ 8.1 FLT Ri LU;681;;MQ 8.2 FLT Ri Neuhermsheim;843;
16.05.2023 17:00;MQ 8.1 FLT Ri LU;700;;MQ 8.2 FLT Ri Neuhermsheim;993;
16.05.2023 18:00;MQ 8.1 FLT Ri LU;701;;MQ 8.2 FLT Ri Neuhermsheim;931;
16.05.2023 19:00;MQ 8.1 FLT Ri LU;664;;MQ 8.2 FLT Ri Neuhermsheim;724;
16.05.2023 20:00;MQ 8.1 FLT Ri LU;445;;MQ 8.2 FLT Ri Neuhermsheim;407;
16.05.2023 21:00;MQ 8.1 FLT Ri LU;318;;MQ 8.2 FLT Ri Neuhermsheim;254;
16.05.2023 22:00;MQ 8.1 FLT Ri LU;264;;MQ 8.2 FLT Ri Neuhermsheim;202;
16.05.2023 23:00;MQ 8.1 FLT Ri LU;259;;MQ 8.2 FLT Ri Neuhermsheim;182;
16.05.2023 23:59;MQ 8.1 FLT Ri LU;465;;MQ 8.2 FLT Ri Neuhermsheim;163;"""
        , '22033', 'link_22033', '191154', 'link_191154'
    ),
    #	<!-- MQ9 Neckarauer ubergang richtung innenstadt-->
    # <!-- MQ9 Neckarauer ubergang richtung neckarau -->
    (
        """16.05.2023 01:00;MQ 9.1 Nug Ri Innenstadt;85;;MQ 9.2 Nug Ri Neckarau;68;
16.05.2023 02:00;MQ 9.1 Nug Ri Innenstadt;54;;MQ 9.2 Nug Ri Neckarau;38;
16.05.2023 03:00;MQ 9.1 Nug Ri Innenstadt;41;;MQ 9.2 Nug Ri Neckarau;23;
16.05.2023 04:00;MQ 9.1 Nug Ri Innenstadt;50;;MQ 9.2 Nug Ri Neckarau;29;
16.05.2023 05:00;MQ 9.1 Nug Ri Innenstadt;79;;MQ 9.2 Nug Ri Neckarau;40;
16.05.2023 06:00;MQ 9.1 Nug Ri Innenstadt;241;;MQ 9.2 Nug Ri Neckarau;154;
16.05.2023 07:00;MQ 9.1 Nug Ri Innenstadt;423,9;;MQ 9.2 Nug Ri Neckarau;320;
16.05.2023 08:00;MQ 9.1 Nug Ri Innenstadt;743,9;;MQ 9.2 Nug Ri Neckarau;517;
16.05.2023 09:00;MQ 9.1 Nug Ri Innenstadt;760;;MQ 9.2 Nug Ri Neckarau;526;
16.05.2023 10:00;MQ 9.1 Nug Ri Innenstadt;672;;MQ 9.2 Nug Ri Neckarau;555;
16.05.2023 11:00;MQ 9.1 Nug Ri Innenstadt;699;;MQ 9.2 Nug Ri Neckarau;589;
16.05.2023 12:00;MQ 9.1 Nug Ri Innenstadt;704,9;;MQ 9.2 Nug Ri Neckarau;581;
16.05.2023 13:00;MQ 9.1 Nug Ri Innenstadt;746,1;;MQ 9.2 Nug Ri Neckarau;706;
16.05.2023 14:00;MQ 9.1 Nug Ri Innenstadt;788;;MQ 9.2 Nug Ri Neckarau;617;
16.05.2023 15:00;MQ 9.1 Nug Ri Innenstadt;757,1;;MQ 9.2 Nug Ri Neckarau;671;
16.05.2023 16:00;MQ 9.1 Nug Ri Innenstadt;848,9;;MQ 9.2 Nug Ri Neckarau;661;
16.05.2023 17:00;MQ 9.1 Nug Ri Innenstadt;784,1;;MQ 9.2 Nug Ri Neckarau;668;
16.05.2023 18:00;MQ 9.1 Nug Ri Innenstadt;788,9;;MQ 9.2 Nug Ri Neckarau;629;
16.05.2023 19:00;MQ 9.1 Nug Ri Innenstadt;743,1;;MQ 9.2 Nug Ri Neckarau;623;
16.05.2023 20:00;MQ 9.1 Nug Ri Innenstadt;535;;MQ 9.2 Nug Ri Neckarau;509;
16.05.2023 21:00;MQ 9.1 Nug Ri Innenstadt;395,1;;MQ 9.2 Nug Ri Neckarau;407;
16.05.2023 22:00;MQ 9.1 Nug Ri Innenstadt;348;;MQ 9.2 Nug Ri Neckarau;342;
16.05.2023 23:00;MQ 9.1 Nug Ri Innenstadt;280,1;;MQ 9.2 Nug Ri Neckarau;260;
16.05.2023 23:59;MQ 9.1 Nug Ri Innenstadt;200;;MQ 9.2 Nug Ri Neckarau;193;"""
        , '204790', 'link_204790', '8337', 'link_8337'
    )
    # ,
    # (
    #       """
    #        16.05.2023 01:00;MQ 10.1 Luf Ri Lindenhof;44;;;;
    # 16.05.2023 02:00;MQ 10.1 Luf Ri Lindenhof;18;;;;
    # 16.05.2023 03:00;MQ 10.1 Luf Ri Lindenhof;18;;;;
    # 16.05.2023 04:00;MQ 10.1 Luf Ri Lindenhof;34;;;;
    # 16.05.2023 05:00;MQ 10.1 Luf Ri Lindenhof;62;;;;
    # 16.05.2023 06:00;MQ 10.1 Luf Ri Lindenhof;299;;;;
    # 16.05.2023 07:00;MQ 10.1 Luf Ri Lindenhof;359;;;;
    # 16.05.2023 08:00;MQ 10.1 Luf Ri Lindenhof;513;;;;
    # 16.05.2023 09:00;MQ 10.1 Luf Ri Lindenhof;546;;;;
    # 16.05.2023 10:00;MQ 10.1 Luf Ri Lindenhof;325,1;;;;
    # 16.05.2023 11:00;MQ 10.1 Luf Ri Lindenhof;215;;;;
    # 16.05.2023 12:00;MQ 10.1 Luf Ri Lindenhof;191;;;;
    # 16.05.2023 13:00;MQ 10.1 Luf Ri Lindenhof;247;;;;
    # 16.05.2023 14:00;MQ 10.1 Luf Ri Lindenhof;288;;;;
    # 16.05.2023 15:00;MQ 10.1 Luf Ri Lindenhof;331;;;;
    # 16.05.2023 16:00;MQ 10.1 Luf Ri Lindenhof;362;;;;
    # 16.05.2023 17:00;MQ 10.1 Luf Ri Lindenhof;419;;;;
    # 16.05.2023 18:00;MQ 10.1 Luf Ri Lindenhof;379,1;;;;
    # 16.05.2023 19:00;MQ 10.1 Luf Ri Lindenhof;275;;;;
    # 16.05.2023 20:00;MQ 10.1 Luf Ri Lindenhof;180;;;;
    # 16.05.2023 21:00;MQ 10.1 Luf Ri Lindenhof;113;;;;
    # 16.05.2023 22:00;MQ 10.1 Luf Ri Lindenhof;94;;;;
    # 16.05.2023 23:00;MQ 10.1 Luf Ri Lindenhof;75;;;;
    # 16.05.2023 23:59;MQ 10.1 Luf Ri Lindenhof;51;;;;""",
    #        '380840','link_380840','NULL','link_NULL'
    #    )

]



def process_dataset(data, loc_id, cs_id, left=True, file_index=1, directory='data'):
    if not os.path.exists(directory):
        os.makedirs(directory)

    # Define the position of the value in data line based on whether it's left or right dataset
    index_position = 2 if left else 5  # Position of value in data line

    def parse_line(line):
        try:
            parts = line.split(';')
            hour = int(parts[0].split()[1].split(':')[0])
            minute = int(parts[0].split()[1].split(':')[1])
            if hour == 23 and minute == 59:
                hour = 0
            parts[index_position].split(',')[0].replace('.', '')
            value_parts = parts[index_position].split(',')
            if len(value_parts) == 2:
                integer_value = int(value_parts[0].replace('.', '')) + int(value_parts[1])
            else:
                integer_value = int(value_parts[0].replace('.', ''))
            print("Successfully processed line:", line)
            return hour, str(integer_value)
        except ValueError:
            print("Error processing line:", line)

    root = ET.Element('count', attrib={'loc_id': loc_id, 'cs_id': cs_id})
    for line in data:
        hour, value = parse_line(line)
        ET.SubElement(root, 'volume', attrib={'h': str(hour), 'val': value})

    # Construct the full path for the output file
    filename = f'output{"left" if left else "right"}_{file_index}.xml'
    filepath = os.path.join(directory, filename)

    tree = ET.ElementTree(root)
    tree.write(filepath, encoding='utf-8', xml_declaration=True)


# Example usage
file_index = 1
for data, loc_idLeft, cs_idLeft, loc_idRight, cs_idRight in data_sets:
    data_lines = data.strip().split('\n')
    process_dataset(data_lines, loc_idLeft, cs_idLeft, left=True, file_index=file_index, directory='output')
    process_dataset(data_lines, loc_idRight, cs_idRight, left=False, file_index=file_index, directory='output')
    file_index += 1  # Increment file index for unique filenames
